"""Apply SQL migrations in filename order.

Why not Alembic: autogenerated diffs hide the actual DDL, and the point of
this project is that you can whiteboard this schema. Plain numbered .sql
files + a tracking table is the whole mental model (ADR-002).

Usage: python scripts/migrate.py
"""

import asyncio
import sys
from pathlib import Path

import asyncpg

# Allow running as a plain script from the repo root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.config import get_settings  # noqa: E402

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "app" / "db" / "migrations"


async def main() -> None:
    settings = get_settings()
    conn = await asyncpg.connect(settings.database_url)
    try:
        await conn.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                filename   TEXT PRIMARY KEY,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
        applied = {
            r["filename"] for r in await conn.fetch("SELECT filename FROM schema_migrations")
        }
        pending = [
            p for p in sorted(MIGRATIONS_DIR.glob("*.sql")) if p.name not in applied
        ]
        if not pending:
            print("Migrations: nothing to apply.")
            return
        for path in pending:
            # Each migration runs in its own transaction: either the whole
            # file applies and is recorded, or neither happens.
            async with conn.transaction():
                await conn.execute(path.read_text(encoding="utf-8"))
                await conn.execute(
                    "INSERT INTO schema_migrations (filename) VALUES ($1)", path.name
                )
            print(f"Applied {path.name}")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
